### ISSUE TITLE
Use Angular2 functionality callback events

### ISSUE THREAD

**Issue by Rudde** [nekken/ng2-fullcalendar#8]
Hello.

When writing callback functions for fullcalendar we can't access angular2 elements. "this" is jquery.fn.init. 

Like when they click on a day the dayClick callback I would like to route the user to a custom page for that route. I can do this with vanilla JS, but that cause a full page reload, not very desirable when Angular2 is a SPA framework and full page reloads are very heavy on it.

**Comment by nekken** [comment]
Hi Rudde,

in order to have access to your component in callbacks, please try the following:

create a function inside your component class called clickday()

function bind :
`{
...,
dayClick: this.clickday.bind(this),
...
}`
OR

fat arrow :
`{
dayClick: (date, jsEvent, view) => this.clickDay(date, jsEvent, view),
}`
you can read more about it here

http://stackoverflow.com/questions/20627138/typescript-this-scoping-issue-when-called-in-jquery-callback

**Comment by Rudde** [comment]
Hello! Thank you very much. Used .bind and it worked as expected.

**Comment by micaz** [comment]
Hi Thank you
